# Generated by Django 4.1.3 on 2022-12-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='FormBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_year', models.FloatField(verbose_name='Sueldo año')),
                ('cesantias', models.FloatField(verbose_name='Cesantías')),
                ('prima', models.FloatField(verbose_name='Prima')),
                ('int_cesantias', models.FloatField(verbose_name='Int. Cesantías')),
                ('vacaciones', models.FloatField(verbose_name='Vacaciones')),
                ('total_prest', models.FloatField(verbose_name='Total Prestaciones')),
                ('salud', models.FloatField(verbose_name='Salud')),
                ('pension', models.FloatField(verbose_name='Pensión')),
                ('arl', models.FloatField(verbose_name='ARL')),
                ('comfama', models.FloatField(verbose_name='Comfama')),
                ('sena', models.FloatField(verbose_name='SENA')),
                ('icbf', models.FloatField(verbose_name='ICBF')),
                ('total_aportes', models.FloatField(verbose_name='Total Aportes')),
                ('typebudget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.typebudget', verbose_name='Tipo de aporte')),
            ],
        ),
    ]
